Repository spicetify/spicetify-docs, pull requests merged in 2022-01, with the labels that each got.

#11 docs: simplify installation process
  docs/getting-started/advanced-installation.md
  docs/getting-started/basic-usage.md
  docs/getting-started/custom-apps.md
  docs/getting-started/extensions.md
  docs/getting-started/simple-installation.md
  docs/getting-started/themes.md
  docusaurus.config.js
  src/pages/index.tsx
Labels: documentation

#16 docs: changed scoop repository
  docs/getting-started/advanced-installation.md
Labels: 🐛 bug, ✏️ documentation

#14 Add initial take at custom apps development page
  docs/development/custom-apps.md
  docs/development/js-modules.md
Labels: ✏️ documentation, 🔧 improvement

#4 [Docs - FAQ] Fix for "Cant play some songs after downgrading spotify"
  docs/faq.md
Labels: ✏️ documentation

#18 fix: add linux and macOS paths & grammar fix.
  docs/faq.md
Labels: ✏️ documentation, 🔧 improvement

#19 bump: `docusaurus` to `2.0.0-beta.15`
  package.json
  yarn.lock
Labels: 📦 dependency
