Repository spicetify/spicetify-docs, pull requests merged in 2022-02, with the labels that each got.

#24 Docs for Spicetify Creator
  docs/development/spicetify-creator/_category_.yaml
  docs/development/spicetify-creator/building-and-testing.md
  docs/development/spicetify-creator/create-custom-apps.md
  docs/development/spicetify-creator/create-extensions.md
  docs/development/spicetify-creator/the-basics.md
Labels: ✏️ documentation

#23 Add image to homepage
  package.json
  src/components/SwiperCarousel.tsx
  src/css/custom.css
  src/pages/index.module.css
  src/pages/index.tsx
  static/img/homepage-carousel/1.png
  static/img/homepage-carousel/2.png
  static/img/homepage-carousel/3.png
  static/img/homepage-carousel/4.png
  static/img/homepage-carousel/5.png
  static/img/homepage-carousel/6.png
  static/img/homepage-carousel/7.png
  yarn.lock
Labels: ✨ design

#28 chore: add powered-by-vercel flare
  README.md
  docusaurus.config.js
  static/img/powered-by-vercel.svg
Labels: ✨ design

#29 chore: updated links to reflect spicetify org
  .gitignore
  blog/authors.yml
  docs/development/compiling.md
  docs/faq.md
  docs/getting-started/advanced-installation.md
  docs/getting-started/custom-apps.md
  docs/getting-started/simple-installation.md
  docusaurus.config.js
Labels: ✏️ documentation

#30 fix: image outside `/` base url
  docusaurus.config.js
Labels: 🐛 bug
